apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: ping-cm
    envs:
      - ping-cm.env
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
