apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ping
            image: image/ping
            imagePullPolicy: IfNotPresent
            command: [ "/bin/sh" ]
            args:
              - -c
              - "ping -c2 ${HOSTNAME}"
            env:
              - name: HOSTNAME
                valueFrom:
                  configMapKeyRef:
                    name: ping-cm
                    key: PING_DST
                    optional: false
            securityContext:
              capabilities:
                add:
                  - NET_RAW
          restartPolicy: OnFailure
